#!/usr/bin/env python
'''
A CLI interface to a remote salt-api instance
'''
from __future__ import print_function

import sys
import logging
import json

from pepper.cli import PepperCli
from pepper import PepperException

try:
    from logging import NullHandler
except ImportError: # Python < 2.7
    class NullHandler(logging.Handler):
        def emit(self, record): pass

try:
    import salt.output
    import salt.config
    __opts__ = salt.config.minion_config('/etc/salt/minion')
    __opts__['color']=True
    __opts__['state_output_diff'] = True
    __opts__['state_verbose'] = False
    SALTLOADED=True
except ImportError:
    SALTLOADED=False

logging.basicConfig(format='%(levelname)s %(asctime)s %(module)s: %(message)s')
logger = logging.getLogger('pepper')
logger.addHandler(NullHandler())

if __name__ == '__main__':
    try:
        cli = PepperCli()
        for exit_code, result in cli.run():
            out = cli.options.__dict__.get('output')
            if SALTLOADED and out is not None:
                try:
                    salt.output.display_output(json.loads(result), out, opts=__opts__)
                except:
                    print(result)
            else:
                print(result)
            if exit_code is not None:
                raise SystemExit(exit_code)
    except PepperException as exc:
        print('Pepper error: {0}'.format(exc), file=sys.stderr)
        raise SystemExit(1)
    except KeyboardInterrupt:
        # TODO: mimic CLI and output JID on ctrl-c
        raise SystemExit(0)
    except Exception as e:
        print(e)
        print('Uncaught Pepper error (increase verbosity for the full traceback).',
                file=sys.stderr)
        logger.debug('Uncaught traceback:', exc_info=True)
        raise SystemExit(1)
